import { Metadata } from "next";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by PHAM QUANG TRUONG",
};

export default function Home() {
  return (
    <>
    </>
  );
}
